# Le pivot de gauss

## Matrice de transvection

In [1]:
import numpy as np
import scipy as sp

In [2]:
def mat_transvection(n,i,j,a):
    In=np.eye(n)
    Eij=np.zeros((n,n))
    Eij[i,j]=1
    return In+a*Eij
    
    

In [3]:
mat_transvection(5,2,3,5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  5.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [4]:
A=np.array([[4,5,14],[1,11,23],[0,2,-5]])
T=mat_transvection(3,0,2,1)
A

array([[ 4,  5, 14],
       [ 1, 11, 23],
       [ 0,  2, -5]])

In [5]:
T

array([[ 1.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [6]:
res_g=np.dot(T,A)

In [7]:
res_g#somme des 2 lignes (i,j)

array([[  4.,   7.,   9.],
       [  1.,  11.,  23.],
       [  0.,   2.,  -5.]])

In [8]:
res_d=np.dot(A, T)
res_d#somme des deux colonnes(i,j)

array([[  4.,   5.,  18.],
       [  1.,  11.,  24.],
       [  0.,   2.,  -5.]])

## Matrice de permutation

In [9]:
def mat_permutation(n,i,j):
    In=np.eye(n)
    per=In[[i]]
    In[i]=In[j]
    In[j]=per
    return In

In [10]:
P=mat_permutation(3,0,2)
P

array([[ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.]])

In [11]:
A

array([[ 4,  5, 14],
       [ 1, 11, 23],
       [ 0,  2, -5]])

In [12]:
per_g=np.dot(P,A)
per_g #permutation des lignes(i et j)

array([[  0.,   2.,  -5.],
       [  1.,  11.,  23.],
       [  4.,   5.,  14.]])

In [13]:
per_d=np.dot(A, P)
per_d#permutation des colonnes(i et j)

array([[ 14.,   5.,   4.],
       [ 23.,  11.,   1.],
       [ -5.,   2.,   0.]])

## Pivot de Gauss

In [14]:
A=np.ones((4,4))
A[[1,1,2,2,3,3,3],[2,3,1,3,1,2,3]]=-1
iden=np.eye(4)

In [15]:
iden

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [16]:
A

array([[ 1,  1,  1,  1],
       [ 1,  1, -1, -1],
       [ 1, -1,  1, -1],
       [ 1, -1, -1, -1]])

In [17]:
T1=mat_transvection(4,0,3,1)
A1=np.dot(T1,A)
inv1=np.dot(T1,iden)
A1

array([[ 2.,  0.,  0.,  0.],
       [ 1.,  1., -1., -1.],
       [ 1., -1.,  1., -1.],
       [ 1., -1., -1., -1.]])

In [18]:
T2=mat_transvection(4,3,0,1)
A2=np.dot(A1,T2)
inv2=np.dot(inv1,T2)
A2

array([[ 2.,  0.,  0.,  0.],
       [ 0.,  1., -1., -1.],
       [ 0., -1.,  1., -1.],
       [ 0., -1., -1., -1.]])

In [19]:
T3=mat_transvection(4,1,3,-1)
A3=np.dot(T3,A2)
inv3=np.dot(T3,inv2)
A3

array([[ 2.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.],
       [ 0., -1.,  1., -1.],
       [ 0., -1., -1., -1.]])

In [20]:
T4=mat_transvection(4,2,3,-1)
A4=np.dot(T4,A3)
inv4=np.dot(T4,inv3)
A4

array([[ 2.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0., -1., -1., -1.]])

In [21]:
T5=mat_transvection(4,3,1,-1)
A5=np.dot(A4,T5)
inv5=np.dot(inv4,T5)
A5

array([[ 2.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0.,  0., -1., -1.]])

In [22]:
T6=mat_transvection(4,3,2,-1)
A6=np.dot(A5,T6)
inv6=np.dot(inv5,T6)
A6

array([[ 2.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0.,  0.,  0., -1.]])

In [23]:
T7=mat_transvection(4,3,3,-3)
A7=np.dot(T7,A6)
inv7=np.dot(T7,inv6)
A7

array([[ 2.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0.,  0.,  0.,  2.]])

In [24]:
T8=mat_transvection(4,0,0,-(1/2))
A8=np.dot(T8,A7)
inv8=np.dot(T8,inv7)
A8

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0.,  0.,  0.,  2.]])

In [25]:
T9=mat_transvection(4,1,1,-(1/2))
A9=np.dot(T9,A8)
inv9=np.dot(T9,inv8)
A9

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0.,  0.,  0.,  2.]])

In [26]:
T10=mat_transvection(4,2,2,-(1/2))
A10=np.dot(T10,A9)
inv10=np.dot(T10,inv9)
A10

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  2.]])

In [27]:
T11=mat_transvection(4,3,3,-(1/2))
A11=np.dot(T11,A10)
inv11=np.dot(T11,inv10)
A11

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [28]:
inv11

array([[ 1. , -0.5, -0.5,  0.5],
       [-0.5,  1. ,  0.5, -0.5],
       [-0.5,  0.5,  1. , -0.5],
       [-1. ,  1. ,  1. , -1. ]])

In [207]:
np.linalg.inv(A)

array([[ 0.5,  0. ,  0. ,  0.5],
       [-0. ,  0.5, -0. , -0.5],
       [-0. , -0. ,  0.5, -0.5],
       [ 0.5, -0.5, -0.5,  0.5]])

In [206]:
np.dot(A, a_inv)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])